remote_theme: coursweb/jk-theme
title: Teams pour l'enseignement
description: Utilisation de Teams dans l'enseignement
lang: fr-FR
robots: noindex, nofollow
chapters:
 # - title: Cours-web
 #  url: https://cours-web.ch/
  - title: Infos IMD
    url: https://code.eracom-pedagogique.ch/infos-profs-imd/
  - title: Pédagogie
    url: https://code.eracom-pedagogique.ch/pedagogie/
  - title: Livres
    url: https://code.eracom-pedagogique.ch/livres-imd/
  - title: Fontes
    url: https://code.eracom-pedagogique.ch/fontes-imd/
  - title: Teams
    url: https://code.eracom-pedagogique.ch/teams-enseignement/
   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2022-2023</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/eracom/teams-enseignement">Lien Github</a></li></ul>
